version: '3.8'
services:
  frontend:
    container_name: nextjs-frontend
    restart: always
    build: 
      context: frontend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  backend:
    container_name: express-backend
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    command: npm run start
    environment:
      - POSTGRES_HOST= host.docker.internal

    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
    - .:/usr/src/app

  db:
    container_name: postgres-database
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD= password
      - POSTGRES_USER= postgres
      - POSTGRES_DB= postgres

volumes: 
  data: {}