version: '3.8'
services:
  backend:
    container_name: express-backend
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm run build
    depends_on:
      - db
    volumes:
    - .:/usr/src/app

  db:
    container_name: postgres-database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD= password
      - POSTGRES_USER= postgres
      - POSTGRES_DB= postgres